app: shop-nodejs-backend
service: import-service

frameworkVersion: '3'
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
    authorizers:
      basicAuthorizer:
        type: request
        functionArn: '${cf:authorization-service-dev.basicAuthorizerArn}'
        identitySource: $request.header.Authorization
        resultTtlInSeconds: 0
        enableSimpleResponses: true
        managedExternally: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:*'
          Resource:
            - 'arn:aws:s3:::${env:BUCKET}/*'
        - Effect: Allow
          Action:
            - sqs:*
          Resource:
            - '${cf:products-service-dev.getCatalogItemsQueueArn}'
  environment:
    SQS_URL:
      - '${cf:products-service-dev.getCatalogItemsQueueRef}'

package:
  individually: true 
  patterns:
    - './build/main.js'
    - '!./src'
    - '!./*'
    - '!./node_modules'

functions:
  importProductsFile:
    handler: build/main.importProductsFile
    events:
      - httpApi:
          path: /import/{name}
          method: get
          authorizer:
            name: basicAuthorizer
    environment: ${file(env.json)}
  importFileParser:
    handler: build/main.importFileParser
    events:
      - s3:
          bucket: ${env:BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
    environment: ${file(env.json)}
