app: shop-nodejs-backend
service: import-service

frameworkVersion: '3'
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:*'
          Resource:
            - 'arn:aws:s3:::${env:BUCKET}/*'
        - Effect: Allow
          Action:
            - sqs:*
          Resource:
            - '${cf:products-service-dev.getCatalogItemsQueueArn}'
  environment:
    - ${file(env.json)}
    SQS_URL:
      - '${cf:products-service-dev.getCatalogItemsQueueRef}'

package:
  individually: true 
  patterns:
    - './build/main.js'
    - '!./src'
    - '!./*'
    - '!./node_modules'

functions:
  importProductsFile:
    handler: build/main.importProductsFile
    events:
      - httpApi:
          path: /import/{name}
          method: get
  importFileParser:
    handler: build/main.importFileParser
    events:
      - s3:
          bucket: ${env:BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
